server {
    listen 3000;

    location /api/ {
        proxy_pass http://mern-back:5000;
        proxy_set_header Host $host;
    }

    location /uploads/ {
        proxy_pass http://mern-back:5000;
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}
